import { Prisma, PrismaClient } from "@prisma/client";
import { PrismaClientKnownRequestError } from "@prisma/client/runtime/client";
import {
    getPaginationMetadata,
    getPopulateOptions,
    getPrismaClient,
    mapPrismaErrorToHttpError,
    setPaginationAndPopulation
} from "@utils/adapters/prisma";
import { FindOptions, PaginateOptions } from "@utils/helpers/exz";
import { PaginateDatasourceDTO } from "@DTOs/paginate/PaginateDTO";

/**
 * Type that manages all the clients for every model
 */
type PrismaDelegate<K extends keyof PrismaClient> = PrismaClient[K];

/**
 * Type that contains all the uncapitalized model name generated by Prisma
 */
type PrismaModelKey = Uncapitalize<Prisma.ModelName> & keyof PrismaClient;

/**
 * Type that contains the model given a Delegate
 */
type DelegateEntity<D> =
    D extends { findFirstOrThrow: (...args: any) => Prisma.PrismaPromise<infer R> } ? R : never;

/**
 * Type that contains the WhereInput of the model given a Delegate
 */
type DelegateWhereInput<D> =
    D extends { findMany: (args?: infer A) => any }
        ? A extends { where?: infer W } ? W : never
        : never;

/**
 * Type that contains the WhereUniqueInput of the model given a Delegate
 */
type DelegateWhereUniqueInput<D> =
    D extends { findUnique: (args: infer A) => any }
        ? A extends { where: infer W } ? W : never
        : never;

/**
 * Maps an uncapitalized model key (e.g. "log") to the Prisma.ModelName (e.g. "Log")
 */
type CapitalizeModelKey<K extends PrismaModelKey> = Capitalize<K> & Prisma.ModelName;

/**
 * Extracts the CreateInput type from Prisma's TypeMap for a given model key.
 */
type DelegateCreateInput<K extends PrismaModelKey> =
    NonNullable<Prisma.TypeMap['model'][CapitalizeModelKey<K>]['operations']['create']['args']['data']>;

/**
 * Extracts the UpdateInput type from a Prisma delegate's create method.
 */
type DelegateUpdateInput<D> =
    D extends { update: (args: infer A) => any }
        ? A extends { data: infer C } ? C : never
        : never;

/**
 * Extracts the DelegateSelect type from a Prisma delegate's create method.
 */
type DelegateSelect<D> =
    D extends { update: (args: infer A) => any }
        ? A extends { select: infer C } ? C : never
        : never;

/**
 * Extracts the DelegateInclude type from a Prisma delegate's create method.
 */
type DelegateInclude<D> =
    D extends { update: (args: infer A) => any }
        ? A extends { include: infer C } ? C : never
        : never;

/**
 * Extracts the DelegateOmit type from a Prisma delegate's findMany method.
 */
type DelegateOmit<D> =
    D extends { findMany: (args?: infer A) => any }
        ? A extends { omit?: infer C } ? C : never
        : never;

/**
 * Filters out relation fields (objects) from a type, keeping only scalar fields.
 * This prevents nested relation creates (e.g. roles: { createMany: ... }) in the base save().
 */
type ScalarOnly<T> = {
    [K in keyof T as NonNullable<T[K]> extends object ? never : K]: T[K];
};

export abstract class BaseRepository<
    K extends PrismaModelKey,
    D = PrismaDelegate<K>,
    Entity = DelegateEntity<D>,
    Where = DelegateWhereInput<D>,
    WhereUnique = DelegateWhereUniqueInput<D>,
    Create = DelegateCreateInput<K>,
    CreateScalar = ScalarOnly<DelegateCreateInput<K>>,
    UpdateInput = ScalarOnly<DelegateUpdateInput<D>>,
    Include = DelegateInclude<D>,
    Select = DelegateSelect<D>,
    Omit = DelegateOmit<D>,
> {
    protected readonly delegate: D;

    protected constructor(protected readonly modelKey: K) {
        this.delegate = getPrismaClient()[modelKey] as D;
    }

    /**
     * Returns the delegate, optionally scoped to a transaction. Useful instead of writing everytime (tx ?? getPrismaClient().clientin ev)
     */
    protected getDelegate(tx?: Prisma.TransactionClient): D {
        if (tx) {
            return (tx as any)[this.modelKey] as D;
        }
        return this.delegate;
    }

    /**
     * Fancy way to wrap every operation in the utility function mapPrismaErrorToHttpError
     */
    protected async exec<R>(fn: () => Promise<R>): Promise<R> {
        try {
            return await fn();
        } catch (err) {
            throw mapPrismaErrorToHttpError(err as PrismaClientKnownRequestError);
        }
    }

    async save(data: CreateScalar, tx?: Prisma.TransactionClient): Promise<Entity> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).create({ data,  })
        );
    }

    async saveWithRelations(data: Create, tx?: Prisma.TransactionClient): Promise<Entity> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).create({ data })
        );
    }

    async update(where: Where, data: UpdateInput, include?: Include, select?: Select, tx?: Prisma.TransactionClient): Promise<Entity> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).update({ where, data, include, select })
        );
    }

    async findOne(query: Where, options?: FindOptions, tx?: Prisma.TransactionClient): Promise<Entity | null> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).findFirst({
                where: query,
                include: options?.populate ? getPopulateOptions(options.populate) : undefined,
            })
        );
    }

    async findMany(
        query: Where,
        options?: FindOptions & {
            orderBy?: any;
            include?: Include;
            select?: Select;
            omit?: Omit;
        },
        tx?: Prisma.TransactionClient,
    ): Promise<Entity[]> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).findMany({
                where: query,
                include: options?.include ?? (options?.populate ? getPopulateOptions(options.populate) : undefined),
                select: options?.select,
                omit: options?.omit,
                orderBy: options?.orderBy,
            })
        );
    }
    
    async deleteById(id: number, tx?: Prisma.TransactionClient): Promise<Entity> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).delete({ where: { id } })
        );
    }

    async deleteOne(query: WhereUnique, tx?: Prisma.TransactionClient): Promise<Entity> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).delete({ where: query })
        );
    }

    async count(query?: Where, tx?: Prisma.TransactionClient): Promise<number> {
        return this.exec(() =>
            (this.getDelegate(tx) as any).count({ where: query })
        );
    }

    async paginate(query: Where, options: PaginateOptions, tx?: Prisma.TransactionClient): Promise<PaginateDatasourceDTO<Entity>> {
        const delegate = this.getDelegate(tx) as any;
        return this.exec(async () => {
            const docs = await delegate.findMany({
                where: query,
                ...setPaginationAndPopulation(options),
            });
            const totalDocs = await delegate.count({ where: query });
            return {
                docs,
                ...getPaginationMetadata(options, totalDocs),
            } as PaginateDatasourceDTO<Entity>;
        });
    }
}